# A basic example workflow to show how you can auto-run scripts to organise
# your Instapaper unread articles.
name: SortBookmarks

# Controls when the workflow will run
on:

  schedule:
  - cron: "15 21 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sort-it"
  sortit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Beyond standard Perl, we need one additional module
      - uses: perl-actions/install-with-cpanm@stable
        with:
          install: |
            Net::OAuth::Simple

      # Import our required secrets to environment ready for the script to run
      - name: Run a multi-line script
        env:
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          X_AUTH_USERNAME: ${{ secrets.X_AUTH_USERNAME }}
          X_AUTH_PASSWORD: ${{ secrets.X_AUTH_PASSWORD }}
        run: |
          echo "Running with $CLIENT_KEY key"
          PERL5LIB=lib perl examples/bookmarks-to-folder.pl
